version: '3.8'

services:
  database:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  flask_app:
    build: .
    command: gunicorn app:app --bind 0.0.0.0:4200
    volumes:
      - .:/code
    ports:
      - "4200:4200"
    depends_on:
      - database

  nginx:
    image: nginx:1.19.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask_app


volumes:
  postgres_data: