# Generated by Django 4.2.3 on 2023-07-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_books_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='books',
            unique_together={('title', 'author')},
        ),
    ]
