# Generated by Django 4.2.3 on 2023-07-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchases_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'ordering': ['-date']},
        ),
    ]
