# Generated by Django 4.2.3 on 2023-08-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_purchases_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'ordering': ['-date'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
